import argparse
from pathlib import Path

from hava.compiler import HavaCompiler
from hava.errors import HavaError
from hava.parser import HavaParser, HavaLexer
from hava.vm import HavaVM

lexer = HavaLexer()
parser = HavaParser()
vm = HavaVM()
cli_args_init = argparse.ArgumentParser()
cli_args_init.add_argument("--file", help="Path to a .hava file to run.", type=str)
cli_args_init.add_argument("--ast", help="Print generated AST.", action="store_true")
cli_args_init.add_argument("--bytecode", help="Print generated bytecode.", action="store_true")
cli_args_init.add_argument("--debug", help="Print AST and bytecode.", action="store_true")
cli_args = cli_args_init.parse_args()

def process_tree(source):
    lexer.source = source
    lexer.lineno = 1
    parser.source = source
    tree = parser.parse(lexer.tokenize(source))
    if tree is None:
        return None
    if cli_args.ast or cli_args.debug:
        print("AST", tree)
    compiler = HavaCompiler()
    bytecode = compiler.compile(tree)
    if cli_args.bytecode or cli_args.debug:
        for index, instruction in enumerate(bytecode):
            if instruction.arg is None:
                print(f"{index}: {instruction.op.name}")
            else:
                print(f"{index}: {instruction.op.name} {instruction.arg}")
    return bytecode

def hava_reader():
    source = Path(cli_args.file).read_text(encoding="utf-8")
    source_bytecode = process_tree(source)
    if source_bytecode is not None:
        vm.run(source_bytecode)

def hava_repl():
    while True:
        try:
            repl_command = input("Hava REPL > ")
            if not repl_command:
                continue
            if repl_command in ("exit", "quit", "çık"):
                break
            repl_bytecode = process_tree(repl_command)
            if repl_bytecode is not None:
                vm.run(repl_bytecode)
        except KeyboardInterrupt:
            print("\nExiting.")
            break
        except EOFError:
            print("\nExiting.")
            break
        except HavaError as e:
            print(e)
        except Exception as e:
            print(f"Internal error: {e}")

if __name__ == "__main__":
    prelude_path = Path("stdlib/prelude.hava")
    if prelude_path.exists():
        prelude_source = prelude_path.read_text(encoding="utf-8")
        prelude_bytecode = process_tree(prelude_source)
        if prelude_bytecode is not None:
            vm.run(prelude_bytecode)
    if cli_args.file:
        hava_reader()
    else:
        hava_repl()

